spring.application.name=EurekaMainApplication

server.port=8761

# Eureka is a server, so it should not register itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# @FeignClient(name="eureka-client" , path= "api/request"")
