spring.application.name=MainService

server.port=8090


# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# H2 Verilənlər Bazası Konfiqurasiyası
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2

# H2 Console (brauzer üzərindən baxmaq üçün)
spring.spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
